create table if not exists public.analytics_sync_status (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('ga4', 'google_ads', 'meta_ads')),
  account_id text not null,
  ecommerce text not null,
  last_successful_sync timestamptz,
  last_attempt timestamptz,
  sync_status text not null default 'idle'
    check (sync_status in ('idle', 'running', 'success', 'failed')),
  records_processed integer not null default 0 check (records_processed >= 0),
  date_from date,
  date_to date,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint analytics_sync_status_source_account_ecommerce_key
    unique (source, account_id, ecommerce),
  constraint analytics_sync_status_date_range_check
    check (date_from is null or date_to is null or date_from <= date_to)
);

create table if not exists public.ga4_daily (
  id bigint generated by default as identity primary key,
  property_id text not null,
  ecommerce text not null,
  date date not null,
  channel_group text not null default '(not set)',
  source text not null default '(not set)',
  medium text not null default '(not set)',
  campaign text not null default '(not set)',
  device_category text not null default 'unknown',
  active_users bigint not null default 0 check (active_users >= 0),
  new_users bigint not null default 0 check (new_users >= 0),
  sessions bigint not null default 0 check (sessions >= 0),
  engaged_sessions bigint not null default 0 check (engaged_sessions >= 0),
  engagement_rate numeric(12, 8) not null default 0 check (engagement_rate >= 0),
  ecommerce_purchases bigint not null default 0 check (ecommerce_purchases >= 0),
  purchase_revenue numeric(18, 2) not null default 0 check (purchase_revenue >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ga4_daily_dimensions_key unique (
    property_id,
    ecommerce,
    date,
    channel_group,
    source,
    medium,
    campaign,
    device_category
  )
);

create table if not exists public.google_ads_daily (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  ecommerce text not null,
  date date not null,
  campaign_id text not null,
  campaign_name text not null default '(not set)',
  campaign_type text not null default 'unknown',
  impressions bigint not null default 0 check (impressions >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  cost numeric(18, 2) not null default 0 check (cost >= 0),
  conversions numeric(18, 6) not null default 0 check (conversions >= 0),
  conversion_value numeric(18, 2) not null default 0 check (conversion_value >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint google_ads_daily_dimensions_key
    unique (customer_id, ecommerce, date, campaign_id)
);

create table if not exists public.meta_ads_daily (
  id bigint generated by default as identity primary key,
  account_id text not null,
  ecommerce text not null,
  date date not null,
  campaign_id text not null,
  campaign_name text not null default '(not set)',
  adset_id text not null default '(not set)',
  adset_name text not null default '(not set)',
  ad_id text not null default '(not set)',
  ad_name text not null default '(not set)',
  impressions bigint not null default 0 check (impressions >= 0),
  reach bigint not null default 0 check (reach >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  spend numeric(18, 2) not null default 0 check (spend >= 0),
  conversions numeric(18, 6) not null default 0 check (conversions >= 0),
  conversion_value numeric(18, 2) not null default 0 check (conversion_value >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint meta_ads_daily_dimensions_key
    unique (account_id, ecommerce, date, campaign_id, adset_id, ad_id)
);

comment on column public.meta_ads_daily.reach is
  'Métrica no aditiva. No sumar entre campañas, conjuntos o anuncios para obtener alcance total.';
